[Service]
Environment="DOCKERD_ROOTLESS_ROOTLESSKIT_DISABLE_HOST_LOOPBACK=false"
# by default rootless kit starts slirp4netns with this flag true
# this prevents the containers from reaching the host network
