name: shellcheck

on:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install tools
        run: bin/setup /usr/local/bin

      - name: run shellcheck
        run: |
          find bin dotfiles -type f -print0 \
          | xargs -0 grep -lZE '^#! ?/usr/bin/env bash|^#!/usr/bin/env bash|^#! ?/bin/bash' \
          | xargs -0 shellcheck -x
